### ISSUE TITLE
Not working on Simple Function

### ISSUE THREAD

**Issue by frmichetti** [bikk-uk/jest-mock-express#70] opened 2022-03-15 19:46 UTC
function getMessage() {
  return "Games Resume Backend";
}

this not works:
    const showWelcome = (req, res) => {
        res.status(200).send({ message: getMessage() })
    }

//res.status(200) = works
res.status(200).send .. crashs

Error detail:
Uncaught SyntaxError SyntaxError: Unexpected identifier

**Comment by aboyce** [comment] 2022-04-03 15:40
Hello, this looks like a duplicate of #58. I would have a look at that issue as it has more information with a working example in a sandbox repository to double check your set up logic against.

The `status` function returns the response, so I would check that you are not providing an alternative mock as a first check.

There is also a work around linked on #58 (although it should not be required) if the issue is blocking you from progressing.

**Closed as completed by aboyce** 2022-04-03 15:40 UTC
Labels: duplicate
